branch-defaults:
  main:
    environment: capapi4-dev
    group_suffix: null
global:
  application_name: capapi4
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 20 running on 64bit Amazon Linux 2023
  default_region: ap-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
